version: '3.9'
name: 'odm'
        
services:
  odm:
    image: registry.gitlab.com/beerlab/cpc/slam/odm:latest
    container_name: odm
    command: ["/bin/bash", "-ci", "python3 src/dataset_maker.py odm_media/images/docker_image /r1/fix /r1/r1_down_camera/image_raw auto"]
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
    ipc: host
    stdin_open: true
    tty: true
    privileged: true
    network_mode: "host"
    # networks:
    #   - general
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /odm_media:/workspace/odm/odm_media