version: '3.9'
name: 'odm'

# networks:
#   general:
#     attachable: true
#     internal: false
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.33.0/24
        
services:
  odm:
    image: registry.gitlab.com/beerlab/cpc/slam/odm:test-compose
    container_name: odm
    command: ["/bin/bash", "-ci", "python3 src/continious_printer.py odm_media/results/odm_orthophoto/odm_orthophoto.tif"]
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
    ipc: host
    stdin_open: true
    tty: true
    network_mode: "host"
    # networks:
    #   - general
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /odm_media:/workspace/odm/odm_media